"""empty message

Revision ID: 8c1349976da3
Revises: 
Create Date: 2023-04-17 16:15:18.144566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1349976da3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=45), nullable=False),
    sa.Column('firstname', sa.String(length=45), nullable=False),
    sa.Column('lastname', sa.String(length=45), nullable=True),
    sa.Column('phone_number', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('isAdmin', sa.Enum('0', '1'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=45), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('time_zone', sa.Enum('1', '2'), nullable=True),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'person_id')
    )
    op.create_table('event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('calendar_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendar.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'calendar_id', 'category_id', 'person_id')
    )
    op.create_table('personcalendar',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('calendar_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendar.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'person_id', 'calendar_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personcalendar')
    op.drop_table('event')
    op.drop_table('calendar')
    op.drop_table('person')
    op.drop_table('category')
    # ### end Alembic commands ###
